# Generated by Django 2.0.5 on 2018-05-18 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20180517_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
