# Generated by Django 2.0.5 on 2018-05-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20180518_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='username',
            new_name='user_name',
        ),
    ]
