# Generated by Django 2.0.5 on 2018-05-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20180518_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='user_name',
            new_name='username',
        ),
    ]
